--DELETE FROM UserAccount;
--INSERT INTO UserAccount VALUES (CAST(1 as INT), 'tomek', 'password1');
--INSERT INTO UserAccount VALUES (CAST(2 as INT), 'piotrek', 'password2');
--INSERT INTO UserAccount VALUES (CAST(3 as INT), 'adam', 'password3');